### ISSUE TITLE
Delete unused css.

### ISSUE THREAD

**Issue by tawfiknasser** [facn5/SmurfTeam#38]
https://github.com/facn5/SmurfsTeam/blob/a3c25dacface8283b28c15f023060e47e8cb8182/style.css#L35

https://github.com/facn5/SmurfsTeam/blob/a3c25dacface8283b28c15f023060e47e8cb8182/style.css#L248

https://github.com/facn5/SmurfsTeam/blob/a3c25dacface8283b28c15f023060e47e8cb8182/style.css#L254

make sure there is no unused CSS.

Check this link https://purifycss.online/

**Comment by Bear-Coding** [comment]
Fixed
